# Commented sections below can be used to run tests on the CI server
# https://simulatedgreg.gitbooks.io/electron-vue/content/en/testing.html#on-the-subject-of-ci-testing
version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x86
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  # - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  # - choco install yarn --ignore-dependencies
  - git reset --hard HEAD
  - npm install
  - node --version

build_script:
  #- yarn test
  - npm run build

test: off

deploy:
  release: githoard-v$(appveyor_build_version)
  description: "$APPVEYOR_REPO_COMMIT_MESSAGE"
  provider: GitHub
  auth_token:
    secure: "$GH_KEY"
  artifact: /.*\.exe/
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
